package com.dev.marketplace.api.response.dto;

public record ListingResponse(String id,
    String sellerId,
    String title,
    String description,
    double price,
    String currency,
    boolean negotiable,
    String category,
    String subcategory,
    String condition,
    java.util.List<String> images,
    String suburb,
    String state,
    Double latitude,
    Double longitude,
    String status,
    int views,
    int favoritesCount,
    java.time.Instant createdAt) {}
