spring.application.name=marketplace-api

#context path
server.servlet.context-path=/marketplace-api/v1
#port
server.port=8002
#jwt secret
jwt.secret=CpsOwLfL7lhIMXc/aIOYPi6gRXAJbuNMu7OymFP57Oc=
#jwt expiration
jwt.expiration=300000
#log level
logging.level.com.marketplaceau.backend=info
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=DEBUG
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG

#mongodb uri
spring.mongodb.uri=mongodb://localhost:27017/marketplace