spring.application.name=marketplace-api

#context path
server.servlet.context-path=/api/v1
#port
server.port=8002
#jwt secret
jwt.secret=CpsOwLfL7lhIMXc/aIOYPi6gRXAJbuNMu7OymFP57Oc=
#jwt expiration
jwt.expiration=900000
#log level
logging.level.com.marketplaceau.backend=info
#mongodb
spring.data.mongodb.uri=mongodb://localhost:27017/local
